create table person (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(150),
	gender VARCHAR(7) NOT NULL,
	date_of_birth DATE NOT NULL,
	country_of_birth VARCHAR(50) NOT NULL
);
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (1, 'Jedediah', 'Fittis', null, 'Male', '2024-10-02', 'Vietnam');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (2, 'Markus', 'McCurt', null, 'Male', '2024-03-11', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (3, 'Bogart', 'Aleswell', 'baleswell2@cmu.edu', 'Male', '2024-03-07', 'Dominican Republic');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (4, 'Wakefield', 'Janatka', 'wjanatka3@reddit.com', 'Male', '2024-02-01', 'Mexico');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (5, 'Martguerita', 'Arnefield', 'marnefield4@oracle.com', 'Female', '2024-05-02', 'United States');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (6, 'Donnie', 'Bangs', null, 'Male', '2024-05-01', 'Uzbekistan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (7, 'Brion', 'Speedy', 'bspeedy6@tinyurl.com', 'Male', '2024-03-07', 'Poland');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (8, 'Emlyn', 'Swepstone', 'eswepstone7@storify.com', 'Bigender', '2024-11-10', 'Peru');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (9, 'Claudell', 'Bonavia', 'cbonavia8@delicious.com', 'Male', '2024-01-21', 'United States');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (10, 'Sinclare', 'Sturge', 'ssturge9@soup.io', 'Male', '2024-09-03', 'Colombia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (11, 'Raffaello', 'Greson', null, 'Male', '2024-06-05', 'France');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (12, 'Keith', 'Kuhn', 'kkuhnb@abc.net.au', 'Male', '2024-03-31', 'Ukraine');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (13, 'Lemuel', 'Battisson', null, 'Male', '2023-12-08', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (14, 'Sheila', 'Ascraft', null, 'Female', '2024-07-31', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (15, 'Alain', 'Newell', 'anewelle@gravatar.com', 'Male', '2024-08-13', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (16, 'Ardra', 'Emmins', 'aemminsf@harvard.edu', 'Female', '2024-07-25', 'Slovenia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (17, 'Ethelind', 'Capehorn', null, 'Female', '2024-03-15', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (18, 'Franchot', 'Placidi', 'fplacidih@tamu.edu', 'Male', '2024-11-04', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (19, 'Juieta', 'Flobert', null, 'Female', '2023-12-27', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (20, 'Kip', 'Cohn', 'kcohnj@cocolog-nifty.com', 'Male', '2024-03-30', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (21, 'Cash', 'Heffron', 'cheffronk@wordpress.com', 'Male', '2024-06-07', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (22, 'Rodolph', 'Hallibone', 'rhallibonel@biglobe.ne.jp', 'Male', '2024-03-07', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (23, 'Mychal', 'De Blasio', 'mdeblasiom@umn.edu', 'Male', '2024-06-06', 'Cape Verde');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (24, 'Kaylee', 'Crisell', null, 'Female', '2024-08-22', 'Norway');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (25, 'Rodney', 'Richford', null, 'Male', '2024-06-03', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (26, 'Charmain', 'Muldownie', null, 'Female', '2024-02-04', 'Sweden');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (27, 'Orsa', 'Ricioppo', 'oricioppoq@sphinn.com', 'Female', '2024-08-23', 'Canada');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (28, 'Cymbre', 'Cottle', null, 'Female', '2024-02-09', 'South Korea');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (29, 'Zacharia', 'Headly', 'zheadlys@ovh.net', 'Polygender', '2024-03-18', 'Poland');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (30, 'Candie', 'Shimony', 'cshimonyt@wufoo.com', 'Non-binary', '2024-03-11', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (31, 'Moe', 'Skipp', null, 'Male', '2024-05-11', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (32, 'Kingsley', 'Weth', 'kwethv@usa.gov', 'Male', '2024-11-02', 'Philippines');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (33, 'Stu', 'Bott', 'sbottw@yale.edu', 'Male', '2024-10-23', 'Ukraine');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (34, 'Borden', 'Arlow', null, 'Male', '2024-05-22', 'Pakistan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (35, 'Anabel', 'Beed', 'abeedy@answers.com', 'Female', '2024-08-28', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (36, 'Wolfgang', 'Spur', 'wspurz@japanpost.jp', 'Male', '2024-03-01', 'Venezuela');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (37, 'Natalina', 'Bohan', 'nbohan10@wisc.edu', 'Female', '2024-01-22', 'Ukraine');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (38, 'Lemuel', 'Romao', 'lromao11@shutterfly.com', 'Male', '2024-09-28', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (39, 'Vincents', 'Baish', 'vbaish12@slashdot.org', 'Male', '2024-05-05', 'South Africa');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (40, 'Randy', 'Bredee', 'rbredee13@europa.eu', 'Male', '2024-01-11', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (41, 'Ivan', 'Castagno', null, 'Male', '2024-10-30', 'Vietnam');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (42, 'Vilma', 'Tull', 'vtull15@issuu.com', 'Female', '2023-12-17', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (43, 'Leodora', 'Sharratt', 'lsharratt16@bbb.org', 'Female', '2024-03-17', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (44, 'Deena', 'Brigginshaw', 'dbrigginshaw17@va.gov', 'Female', '2024-11-17', 'Iran');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (45, 'Malynda', 'Gilder', null, 'Female', '2024-07-27', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (46, 'Orion', 'Sterke', 'osterke19@dagondesign.com', 'Male', '2024-09-04', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (47, 'Isabeau', 'Streatfield', 'istreatfield1a@mozilla.org', 'Female', '2024-08-21', 'Philippines');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (48, 'Sayre', 'O''Nions', 'sonions1b@vimeo.com', 'Female', '2024-10-21', 'France');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (49, 'Tarah', 'Hobble', 'thobble1c@nps.gov', 'Female', '2023-12-21', 'Greece');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (50, 'Rik', 'Snelgar', 'rsnelgar1d@1und1.de', 'Male', '2024-01-06', 'Bhutan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (51, 'Mariel', 'Kinnon', null, 'Polygender', '2024-09-25', 'Greece');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (52, 'Kris', 'Strickett', 'kstrickett1f@weebly.com', 'Female', '2024-01-11', 'Philippines');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (53, 'Glenn', 'Slayny', null, 'Female', '2023-12-16', 'Philippines');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (54, 'Mose', 'Casella', 'mcasella1h@amazonaws.com', 'Male', '2024-03-28', 'United States');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (55, 'Keely', 'Matevosian', 'kmatevosian1i@jimdo.com', 'Female', '2023-11-25', 'Japan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (56, 'Kassandra', 'Ruckledge', null, 'Bigender', '2024-02-24', 'South Africa');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (57, 'Friedrick', 'De Cleen', null, 'Male', '2024-05-19', 'Nigeria');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (58, 'Gail', 'Kunrad', 'gkunrad1l@weather.com', 'Female', '2023-12-31', 'Syria');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (59, 'Kerk', 'Velde', 'kvelde1m@a8.net', 'Male', '2024-11-01', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (60, 'Whitman', 'Best', null, 'Male', '2024-06-06', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (61, 'Olga', 'Arguile', null, 'Female', '2024-09-18', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (62, 'Baldwin', 'Scinelli', 'bscinelli1p@vkontakte.ru', 'Male', '2024-05-03', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (63, 'Barnabe', 'Bram', null, 'Male', '2024-08-13', 'Canada');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (64, 'Ara', 'Pakenham', 'apakenham1r@wikipedia.org', 'Male', '2024-04-11', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (65, 'Joey', 'Glendining', null, 'Male', '2024-02-17', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (66, 'Delphine', 'Kinglake', 'dkinglake1t@dyndns.org', 'Female', '2024-07-27', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (67, 'Harvey', 'Mockler', null, 'Male', '2024-05-05', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (68, 'Harmonie', 'Fearnyhough', 'hfearnyhough1v@privacy.gov.au', 'Female', '2024-06-14', 'Nigeria');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (69, 'Rowen', 'Guice', 'rguice1w@ed.gov', 'Male', '2024-03-06', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (70, 'Silvain', 'Elverston', 'selverston1x@patch.com', 'Male', '2024-11-20', 'Philippines');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (71, 'Fairleigh', 'D''Emanuele', 'fdemanuele1y@homestead.com', 'Male', '2024-03-10', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (72, 'Blane', 'Catherall', 'bcatherall1z@state.gov', 'Male', '2024-05-25', 'France');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (73, 'Des', 'McClenaghan', null, 'Male', '2024-05-08', 'Japan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (74, 'Amanda', 'Shuker', 'ashuker21@ted.com', 'Female', '2024-01-03', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (75, 'Carny', 'Matussow', 'cmatussow22@census.gov', 'Male', '2024-10-15', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (76, 'Chuck', 'Pelcheur', 'cpelcheur23@facebook.com', 'Male', '2024-06-30', 'Cuba');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (77, 'Rodrique', 'Tonner', 'rtonner24@com.com', 'Male', '2024-01-19', 'Slovenia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (78, 'Georgina', 'Itzkovici', 'gitzkovici25@is.gd', 'Genderfluid', '2024-07-22', 'Afghanistan');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (79, 'Hube', 'O'' Meara', 'homeara26@canalblog.com', 'Male', '2024-01-18', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (80, 'Karen', 'Father', 'kfather27@miitbeian.gov.cn', 'Female', '2024-04-14', 'Philippines');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (81, 'Werner', 'Greatrakes', null, 'Bigender', '2024-07-10', 'Bulgaria');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (82, 'Joni', 'Gathercole', 'jgathercole29@oracle.com', 'Female', '2024-10-08', 'Faroe Islands');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (83, 'Gunther', 'Mityukov', null, 'Male', '2024-01-27', 'Portugal');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (84, 'Shanna', 'Hofler', null, 'Female', '2024-05-11', 'China');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (85, 'Bobbee', 'Dran', 'bdran2c@apache.org', 'Female', '2024-06-17', 'Brazil');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (86, 'Giuditta', 'Pulfer', null, 'Female', '2024-02-22', 'Uganda');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (87, 'Jemmy', 'Kaley', null, 'Female', '2023-11-30', 'Argentina');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (88, 'Gert', 'Beville', 'gbeville2f@si.edu', 'Female', '2024-08-10', 'Peru');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (89, 'Ronnica', 'Holbury', 'rholbury2g@jalbum.net', 'Female', '2024-07-17', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (90, 'Ketty', 'Kolodziejski', 'kkolodziejski2h@about.me', 'Female', '2024-01-14', 'Moldova');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (91, 'Haze', 'Boutton', 'hboutton2i@webs.com', 'Male', '2024-08-12', 'Russia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (92, 'Beatrisa', 'Wilkisson', 'bwilkisson2j@mashable.com', 'Female', '2024-05-08', 'Sweden');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (93, 'Donelle', 'Heale', null, 'Female', '2024-09-01', 'Belgium');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (94, 'Devy', 'Giorgetti', 'dgiorgetti2l@google.com.hk', 'Male', '2024-10-15', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (95, 'Magdalen', 'Mundall', null, 'Female', '2023-12-23', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (96, 'Monty', 'Gracewood', 'mgracewood2n@wired.com', 'Male', '2024-07-14', 'Czech Republic');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (97, 'Jordanna', 'Werndly', 'jwerndly2o@usnews.com', 'Female', '2024-07-28', 'Colombia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (98, 'Loella', 'Alesio', 'lalesio2p@discovery.com', 'Female', '2024-04-28', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (99, 'Larina', 'Deverale', null, 'Female', '2024-05-11', 'France');
insert into person (id, first_name, last_name, email, gender, date_of_birth, country_of_birth) values (100, 'Candice', 'Epple', null, 'Female', '2024-06-17', 'Russia');
